version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: glamgrove
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: yourpassword
      DB_NAME: glamgrove
      DB_PORT: 5432
    ports:
      - "8080:8080"

volumes:
  postgres_data:
