apiVersion: apps/v1
kind: Deployment
metadata:
  name: glamgrove-deployment
  labels:
    app: glamgrove
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glamgrove
  template:
    metadata:
      labels:
        app: glamgrove
    spec:
      containers:
      - name: glamgrove
        image: glamgrove/glamgrove:latest  
        ports:
        - containerPort: 8000  
        env:
        - name: DB_HOST
          value: "postgres-service"  
        - name: DB_NAME
          value: "glamgrove"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_password
