apiVersion: apps/v1
kind: Deployment
metadata:
  name: glamgrove-deployment
  labels:
    app: glamgrove
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glamgrove
  template:
    metadata:
      labels:
        app: glamgrove
    spec:
      containers:
      - name: glamgrove
        image: glamgrove/glamgrove:latest  
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "postgres-service"  
        - name: DB_NAME
          value: "glamgrove"  # Replace with your PostgreSQL database name
        - name: DB_USER
          value: "postgres"  # Replace with your PostgreSQL username
        - name: DB_PASSWORD
          value: "arya@2002"  # Replace with your PostgreSQL password
