// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"glamgrove/pkg/api"
	"glamgrove/pkg/api/handler"
	"glamgrove/pkg/config"
	"glamgrove/pkg/db"
	"glamgrove/pkg/repository"
	"glamgrove/pkg/usecase"
)

// Injectors from wire.go:

func InitializeApi(cfg config.Config) (*http.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(gormDB)
	adminRepository := repository.NewAdminRepository(gormDB, userRepository)
	productRepository := repository.NewProductRepository(gormDB)

	userService := usecase.NewUserUseCase(userRepository)
	adminService := usecase.NewAdminService(adminRepository)
	productService := usecase.NewProductUseCase(productRepository)

	userHandler := handler.NewUserHandler(userService)
	adminHandler := handler.NewAdminHandler(adminService)
	productHandler := handler.NewProductHandler(productService)

	serverHTTP := http.NewServerHTTP(adminHandler, userHandler, productHandler)
	return serverHTTP, nil
}
