// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"glamgrove/pkg/api"
	"glamgrove/pkg/api/handler"
	"glamgrove/pkg/config"
	"glamgrove/pkg/db"
	"glamgrove/pkg/repository"
	"glamgrove/pkg/usecase"
)

// Injectors from wire.go:

func InitializeApi(cfg config.Config) (*http.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(gormDB)
	adminRepository := repository.NewadminRepository(gormDB)
    //productRepository := repository.NewProductRepository(gormDB)


	userUseCase := usecase.NewUserUseCase(userRepository)
	adminUseCase := usecase.NewadminUseCase(adminRepository)
	//productUseCase := usecase.NewProductUseCase(productRepository)

	userHandler := handler.NewUserHandler(userUseCase)
	adminHandler := handler.NewAdminHandler(adminUseCase)
	//productHandler := handler.NewProductHandler(productUseCase)

	serverHTTP := http.NewServerHTTP(userHandler,adminHandler)
	return serverHTTP, nil
}
