name: Glamgrove-Ecommerce CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.4'

    - name: Install Make
      run: |
        sudo apt update
        sudo apt install -y make

    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Deploy to AWS EC2
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_TWO }}
        PUBLIC_IP: ${{ secrets.PUBLIC_IP_2 }}
      run: |
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ubuntu@$PUBLIC_IP << 'EOF'
          cd glamgrove-ecommerce-project
          git pull
          make build
          sudo systemctl restart glamgrove.service
        EOF
      shell: bash